name: Metrics
on:
  schedule: [{cron: "*/5 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  topics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          plugin_topics: yes
          plugin_topics_mode: icons
      - uses: actions/upload-artifact@v4
        with:
          name: topics-svg
          path: metrics.plugin.topics.icons.svg

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.repositories.svg
          token: ${{ secrets.GH_PAT }}
          plugin_repositories: yes
          plugin_repositories_featured: eschan145/astro,eschan145/stl
      - uses: actions/upload-artifact@v4
        with:
          name: repositories-svg
          path: metrics.plugin.repositories.svg

  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.GH_PAT }}
          plugin_languages: yes
          plugin_languages_indepth: yes
      - uses: actions/upload-artifact@v4
        with:
          name: languages-svg
          path: metrics.plugin.languages.svg

  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.GH_PAT }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: actions/upload-artifact@v4
        with:
          name: isocalendar-svg
          path: metrics.plugin.isocalendar.fullyear.svg

  merge_and_push:
    needs: [topics, repositories, languages, isocalendar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: topics-svg
          path: ./metrics/
      - uses: actions/download-artifact@v4
        with:
          name: repositories-svg
          path: ./metrics/
      - uses: actions/download-artifact@v4
        with:
          name: languages-svg
          path: ./metrics/
      - uses: actions/download-artifact@v4
        with:
          name: isocalendar-svg
          path: ./metrics/
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Automated metrics update (parallel)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
