name: Generate star list

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  featured_star_list:
    name: Generate starred list
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons


      - name: Commit generated SVG
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update"
            git push --force
